name = "ZeroInflation"
uuid = "0c1e6033-84c2-4ed7-8148-22964dc8ff73"
authors = ["Philipp Gewessler <p.gewessler@gmx.at> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
